
name: QuickCluster CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Create build and library directory
      run: mkdir build lib
    - name: Build for MacOS
      run: make darwin
      working-directory: 'quickcluster'





